name: Deploy to Hostinger via FTP

on: 
  push:
    branches: [ main ]

permissions:
  contents: read  
  pages: write      
  id-token: write   
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source  
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build      
      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          host: ${{ secrets.HOSTINGER_HOST_FV }}
          username: ${{ secrets.HOSTINGER_USER_FV }}
          key: ${{ secrets.HOSTINGER_KEY_FV }}
          protocol: ftp                     # Change from 'ftp' to 'sftp'
          port: 21   
          server-dir: /
          
