name: Deploy to Hostinger

on:
  push:
    branches: ["main"]   # or your deployment branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use the Node.js version you need

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Zip build for deployment
        run: zip -r finalVersion.zip .next public node_modules package.json package-lock.json

      - name: Upload ZIP as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: finalVersion
          path: finalVersion.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: finalVersion
          path: .

      - name: Deploy to Hostinger via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_KEY }}
          port: 22
          script: |
            cd public_html
            unzip -o ~/finalVersion.zip
            # Optional: restart Node.js app using PM2
            pm2 restart all || pm2 start npm -- start
