name: Deploy to Hostinger

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install deps and build Next.js static export
      - name: Install and Build
        run: |
          npm install
          npm run build
          npm run export

      # Deploy via FTP to Hostinger
      - name: Upload to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.HOSTINGER_HOST_FV }}
          username: ${{ secrets.HOSTINGER_USER_FV }}
          password: ${{ secrets.HOSTINGER_PASS_FV }}
          local-dir: ./out
          server-dir: /public_html
